name: Tag Build and Publish

on:
  release:
    types:
    - published

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.ref_name }}
      push: true
      skip-ci: true
    secrets: inherit
